### PR TITLE
Airfoil analysis

### PR DESCRIPTION
**Pull request by JoeSpencer1**
I have created files for more different real airfoils for a real comparison instead of just doubling the y vectors.

### CODE REVIEW

**Comment by Cardoza2** [comment]
Comments on your glossary/dictionary: 
- The tip and tail of an airfoil have names, it's the leading edge and trailing edge. 
- The lift curve slope isn't typically used to see the total change in lift, because typically you have multiple airfoils along a wing. The lift curve slope only applies for one section (unless of course you do in fact have the same airfoil along the entire wing). 
- Stall can also occur at negative angles of attack.

**Comment by Cardoza2** [comment]
Comments on write up: 
- I wouldn't say that the lift and drag are controlled by equation one. Rather those equations are from the non-dimensionalization of lift and drag, so you can get lift and drag from the coefficients. 
- Equations doesn't need to be capitalized unless it is at the beginning of a sentence. 
- In the beginning you mention changing chord and camber, but not thickness or Reynolds number, then that's what you do... and you don't end up changing chord. So... I'd be consistent. 
- just before table 1 you have an incomplete sentence. 
- It would be interesting to know why the drag isn't the lowest at alpha=0. 
- Does increasing alpha ALWAYS increase lift? What about in the stalled region? 
- Second to last paragraph on page 3, I'm not sure what you meant about plotting on different planes. 
- Bottom of page 3, which graphs shown in figures 1 and 2?  
- When you say critical angle of attack, do you mean zero-lift angle of attack? There are multiple "critical" angles of attack. Some people define the any important angle of attack as a critical angle of attack. Other's define stall as the critical angle of attack. 
- You did such a good job talking about how the Reynolds numb and Camber affect the polars, but then you skimp on the thickness. Did you not have much to say on the thickness? 
- There seems to be some repetition of comments and thoughts throughout, which isn't entirely bad, but it starts to come off as scattered. 
- I think it'd be good if you had a little more on the lift curve slope. Feel free to ask me a little more on this. 
- Wow, that was pretty good. Good job.

**Review by Cardoza2 — APPROVED** [review]
See comments on pull request.

**Comment by JoeSpencer1** [comment]
I am merging this branch back into my main 497-R branch now.

**Pull request merged**
